name: Build

on:
  push:
jobs:
  build-and-publish:
    uses: ./.github/workflows/actions/desh-build-workflow.yml
    with:
      webhook-url: https://openmrs-cd.mekomsolutions.net/generic-webhook-trigger/invoke
    secrets:
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      OCD3_USERNAME: ${{ secrets.OCD3_USERNAME }}
      OCD3_PASSWORD: ${{ secrets.OCD3_PASSWORD }}